language: python
branches:
  only:
  - main
python:
- '3.7'
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install:
- python setup.py install
script:
- python setup.py test
after_failure:
- cat test.log
notifications:
  slack:
    secure: PY7GyhVBacVqytImbrcyKlDY/uVDTtOMMQ8bEDnhbH9XZA7nOD0dXsEffz93tA1ldJd1+0zsnt9itqdk4pYXBMTcZ6uWE5H2j7KIYylQa2A2Sj5GC3/KjrbFGfqMAXYs+rc9rrlqYkwjztu+bnNqTDnq0Y4Pw0YlMs23NT6GlMg=
env:
  global:
  - secure: acMO9M6O5XeTxnu6yhtx114qO56nOo25TOCB4FeyneV9iG/JGDOk0PI82ov44xfnUXsCh+6UYEoDP6UiOnJTq4NXg24NeO9dxWZ6k8Y/KeOasubR0nHrH4QN2tfpmJmtgYGJqxaUAnPdCNkQbOcEiKaqDahxzxnpnk54cyoixhg=
  - secure: O1jB3+f7K4zJ5xybUC99kJ/tVeYSgftWEeOsVwYcn5KwiPO9zNnNvs3YI3nUMghKLkYdxQux6hesCdxgPtCrzNsgHE6Z9hRZfSLVRJmH33EzpHQG+QEBLIqJun9zKTGqM0pnCFmSB284WBbY4adKlSYv8fXeFnFnjY42J7393f8=
  - secure: IpMaXNonQqzXzCPyUsBflSNH8NSA0ajsLHXi5I43Dk2hXTijrvuf37OCAPV+vvhN39Ry5yofFpTIaesreiqWIrGuIEuUslq0zeTTOUWWQ9wwIh5SiSRIgBSQr3CqjPegyAjMlF2hJBP4LSSMpRyyRo3LvRJYakT6yG51NTmhmNU=
  - secure: eTLsh5vX/eQB8Fxd1FNpcOggC+3wZTl+5DU+ESdW/NLTEYzuE1Yr4nBG6tGCAHXBPtJKgNUft8vrOhwLl1D8WdSgZqv0ji6kdpIqR2tFRzWt/j/Emh7XFlMdm5pKrtKj0mdgTSpPXqr4upGQVcl2Dn8JWTfQL183XGlRQH3u1zA=
